export const landing = {
  authdirect: "AuthDirect",
  pricing : "Pricing",
  docs : "Docs",
  team : "Team",
  signup: "Sign Up",
  authentication: "Authentication",
  simple: "made simple",
  line1: "AuthDirect provides you with a full-fledge ready to use authentication solution.",
  line2:"It's simple to use API solution helps you to focus more on your idea, while authDirect handles all of your auth related jobs.",
  listFeature1: "We take care of your user management, sanitise user's input and store it securly for you.",
  listFeature2:"AuthDirect is a simple-to-use, highly flexible and customisable on demand solution for all your needs.",
  listFeature3:"We have a very active support system and we hear you almost instantly.",
  ctahead: "Would you like to hear from us?",
  ctamessage: "Authdirect is a fast developing product. Join our newletters for all the recent updates.",
  bkpctamsg: "We at AuthDirect encourage participation in face-to-face discussion for the better understanding of the product and it's business.",
  bkpsam:"Schedule a meeting",
  sam:"Join Our Newsletter",
  trynow: "Try Now",
  trynowmsg:"AuthDirect gives you a headstart to your development journey of building dream projects."
}